spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/entregas_db
    username: postgres
    password: senha
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    application:
      name: entregas-api